### ISSUE TITLE
ARM version doesn't open on M1 Mac -V3.1

### ISSUE THREAD

**Issue by anciltech** [sn4k3/UVtools#437] opened 2022-03-18 14:26 UTC
After downloading https://github.com/sn4k3/UVtools/releases/download/v3.1.0/UVtools_osx-arm64_v3.1.0.zip the OS auto extracted the program and the only thing that happens after a double click on the program is an Error message showing "The application "UVtools" can't be opened." I am not sure where I could pull logs from to provide more info. 
<img width="279" alt="Screen Shot 2022-03-18 at 15 17 33" src="https://user-images.githubusercontent.com/79978026/159020504-6891a7af-8a70-4fd3-9934-b00de1dff35e.png">

I checked Setting->Security for a confirmation message to allow the app to run, but it was not there. The x64 version opens and runs though. 

<img width="205" alt="Screen Shot 2022-03-18 at 15 17 57" src="https://user-images.githubusercontent.com/79978026/159020867-e4d6d726-c21c-42c5-8760-495c6d71863c.png">

**Comment by sn4k3** [comment] 2022-03-18 16:12
Duplicate of #431 (Read whole post to know the limitation and solution)

**Closed by sn4k3** 2022-03-18 16:12 UTC
Labels: duplicate
