### ISSUE TITLE
[BUG] UI graphics are not aligned or overflow

### ISSUE THREAD

**Issue by X3msnake** [sn4k3/UVtools#112] opened 2020-12-17 12:34 UTC
![image](https://user-images.githubusercontent.com/11083514/102488461-fae23200-4063-11eb-881c-7e04798e1c9f.png)

win10 64.bits

![image](https://user-images.githubusercontent.com/11083514/102488579-29f8a380-4064-11eb-98bc-a16bed54a694.png)

**Comment by sn4k3** [comment] 2020-12-17 15:31
Yes, that is a known bug. Not with uvtools but with GUI framework.
Waiting for a fix from them. That is caused by scaling.

PS: A screenshot from about box (F1) will contain all information about resolutions

**Comment by sn4k3** [comment] 2020-12-25 04:40
GUI framework problem, maybe is fixed on next release rc1, please check (at least the overflow)

**Closed by sn4k3** 2020-12-25 04:40 UTC
