### ISSUE TITLE
[Crash] System.Runtime.InteropServices.COMException (0x80004005): Parâmetro incorreto.

### ISSUE THREAD

**Issue by lucaslealdev** [sn4k3/UVtools#606] opened 2022-11-16 00:00 UTC
```
System.Runtime.InteropServices.COMException (0x80004005): Parâmetro incorreto.
 ---> System.Runtime.InteropServices.COMException (0x80070057): CreateInstance
   at Avalonia.Win32.Interop.UnmanagedMethods.CreateInstance[T](Guid& clsid, Guid& iid) in /_/src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs:line 1266
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass2_0.<ShowFileDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 33
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass2_0.<ShowFileDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 121
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Avalonia.Controls.SaveFileDialog.ShowAsync(Window parent) in /_/src/Avalonia.Controls/SystemDialog.cs:line 71
   at UVtools.WPF.MainWindow.MenuFileSaveAsClicked() in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 994
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 135
Category: Application
File: salsicha_cabeludo.ctb  [Version: 4] [Class: ChituboxFile]
```

# System
UVtools v3.8.0 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: AMD Ryzen 3 2200G with Radeon Vega Graphics    
Processor cores: 4
Memory RAM: 3.73 / 7.95 GB
Runtime: win10-x64
Framework: .NET 6.0.10
AvaloniaUI: 0.10.18
OpenCV: 4.6.0

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe

Machine date time: 11/15/2022 20:57:47
    UTC date time: 11/15/2022 23:57:47

**Comment by sn4k3** [comment] 2022-11-22 00:44
Duplicate of #590

**Closed** 2022-11-22 00:45 UTC
Labels: duplicate, external bug
