### ISSUE TITLE
[BUG] Anycubic Mono X & Exposure Time Finder

### ISSUE THREAD

**Issue by qkdefus** [sn4k3/UVtools#412] opened 2022-01-31 18:35 UTC
## System
 - OS: [e.g. Windows 10 x64 v20H2]
 - Slicer: Lychee
 - Printer: Anycubic Mono X
 - UVtools version: 2.27.7
```

## Describe the bug
When using the exposure time finder iam unable to print anything, the "anycubic mono x" looks to be printing sequential bottom layers fine. but last time i checked the printer mid print it was printing in the air almost 5cm above the VAT

**Comment by sn4k3** [comment] 2022-01-31 18:36
Duplicate of: https://github.com/sn4k3/UVtools/issues/387
Currently doesnt work for anycubic machines

**Closed** 2022-01-31 18:37 UTC
Labels: duplicate
