### ISSUE TITLE
[Crash] System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by cprice-lci** [sn4k3/UVtools#771] opened 2023-10-17 19:00 UTC
### System

```Text
UVtools v4.0.2 Arm64
Operative system: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 Arm64
Processor: Apple M1 Pro
Processor cores: 10
Memory RAM: 12.34 / 27.63 GB
Runtime: osx.13-arm64
Framework: .NET 6.0.22
AvaloniaUI: 11.0.4
OpenCV: 4.8.0

Path:       /Applications/UVtools.app/Contents/MacOS/
Executable: /Applications/UVtools.app/Contents/MacOS/UVtools
```

### Printer and Slicer

- Printer: Saturn 2
- Slicer: Lychee Slicer 5.3.2

### Description of the bug

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at Avalonia.Rendering.Composition.Server.ServerCompositor.NotifyBatchesProcessed()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.Render()
   at Avalonia.Media.MediaContext.SyncCommit(Compositor compositor, Boolean waitFullRender)
   at Avalonia.Rendering.Composition.CompositingRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Paint()
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.Paint(Void* this)
--- End of stack trace from previous location ---
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at UVtools.UI.Program.Main(String[] args) in UVtools.UI/Program.cs:line 174
Category: Application
File: Corgi presupported_Corgi .ctb  [Version: 0] [Class: CTBEncryptedFile]

Machine date time: 10/17/2023 2:59:53 PM
    UTC date time: 10/17/2023 6:59:53 PM
```

### How to reproduce

Launched UVTools from Lychee Slicer.

**Comment by sn4k3** [comment] 2023-10-17 19:33
Duplicate of #762

**Closed by sn4k3** 2023-10-17 19:33 UTC
Labels: duplicate
