### ISSUE TITLE
M1 Mac error

### ISSUE THREAD

**Issue by SmartDucksWorks** [sn4k3/UVtools#593] opened 2022-10-29 17:01 UTC
UVtools v3.7.2 Arm64 [macOS]
Unable to run due one or more missing dependencies.
Triggered by: libcvextern  (OpenCV)

**Comment by sn4k3** [comment] 2022-10-29 17:04
Duplicate of: https://github.com/sn4k3/UVtools/issues/431
Read: https://github.com/sn4k3/UVtools/discussions/440
Hope to have a workaround on next release

**Closed by sn4k3** 2022-10-29 17:04 UTC
Labels: duplicate
