### ISSUE TITLE
[Crash] System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by sashok1337** [sn4k3/UVtools#768] opened 2023-10-10 19:00 UTC
### System

```Text
UVtools v4.0.2 X64
Operative system: Darwin 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 X64
Processor: Apple M2 Max
Processor cores: 12
Memory RAM: 25.94 / 65.22 GB
Runtime: osx.14-x64
Framework: .NET 6.0.22
AvaloniaUI: 11.0.4
OpenCV: 4.8.0

Path:       /Applications/UVtools.app/Contents/MacOS/
Executable: /Applications/UVtools.app/Contents/MacOS/UVtools
```

### Printer and Slicer

- Printer: Anycubic photon ultra
- Slicer: AnycubicPhotonWorkshop

### Description of the bug

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at Avalonia.Rendering.Composition.Server.ServerCompositor.NotifyBatchesProcessed()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.Render()
   at Avalonia.Media.MediaContext.SyncCommit(Compositor compositor, Boolean waitFullRender)
   at Avalonia.Rendering.Composition.CompositingRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Paint()
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.Paint(Void* this)
--- End of stack trace from previous location ---
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at UVtools.UI.Program.Main(String[] args) in UVtools.UI/Program.cs:line 174
Category: Application
File: Barn_Damage_2.2s.dlp  [Version: 515] [Class: PhotonWorkshopFile]

Machine date time: 10.10.2023 20:58:09
    UTC date time: 10.10.2023 18:58:09
```

### How to reproduce

1. Open file
2. Open "Issues" tab
3. Sometimes it will crash

### Files

[Barn_Damage_2.2s.dlp.zip](https://github.com/sn4k3/UVtools/files/12860935/Barn_Damage_2.2s.dlp.zip)

**Comment by sn4k3** [comment] 2023-10-10 20:42
Duplicate of https://github.com/sn4k3/UVtools/issues/762
Try the solution given on bottom of the post and report back.

**Closed by sn4k3** 2023-10-10 20:42 UTC
Labels: duplicate
