### ISSUE TITLE
[Bug] JSX files do not open 

### ISSUE THREAD

**Issue by tholum** [sn4k3/UVtools#907] opened 2024-07-26 20:21 UTC
### System

```Text
UVtools v4.3.2 Arm64
Operative system: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 Arm64
Processor: Apple M1
Processor cores: 8
Memory RAM: 6.12 / 10.29 GB
Runtime: osx.13-arm64
Framework: .NET 6.0.29
AvaloniaUI: 11.0.10
OpenCV: 4.8.1

Sreens, resolution, working area, usable area:
1: 1440 x 900 @ 100% (Primary)
    WA: 1440 x 818    UA: 1440 x 818

Path:       /Applications/UVtools.app/Contents/MacOS/
Executable: /Applications/UVtools.app/Contents/MacOS/UVtools
```

### Printer and Slicer

- Printer: Uniformation GKTwo
- Slicer: Slicer-2.4.1 ( Uniformation's slicer )

### Description of the bug

When I open any JXS file's I get this error

System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode)
   at UVtools.Core.FileFormats.JXSFile.DecodeInternally(OperationProgress progress) in UVtools.Core/FileFormats/JXSFile.cs:line 419
   at UVtools.Core.FileFormats.FileFormat.Decode(String fileFullPath, FileDecodeType fileDecodeType, OperationProgress progress) in UVtools.Core/FileFormats/FileFormat.cs:line 4232
   at UVtools.UI.MainWindow.<>c__DisplayClass97_0.<ProcessFile>b__2() in UVtools.UI/MainWindow.axaml.cs:line 1431

### How to reproduce

File => Open

### Files

[Phrozen_XP_Finder_V2.jxs.zip](https://github.com/user-attachments/files/16396403/Phrozen_XP_Finder_V2.jxs.zip)

**Comment by sn4k3** [comment] 2024-07-26 20:29
Duplicate of: https://github.com/sn4k3/UVtools/issues/703 (See to resolve)

**Closed** 2024-07-30 21:37 UTC
Labels: duplicate
