### ISSUE TITLE
[FEATURE REQUEST] Exposure Time Finder Optimization

### ISSUE THREAD

**Issue by KleinHorn** [sn4k3/UVtools#393] opened 2022-01-01 00:41 UTC
## Is your feature request related to a problem? Please describe
As it stands, the Multiple Exposures feature exposes each iteration of the model separately. I think a more efficient solution that would save time would be to expose all iterations at once, then turn off the iterations that are no longer necessary.
For example: Lets say we have iterations 1-4 they will be exposed 2s, 4s, 6s, 8s respectively. Why not just expose all iterations for 2s in one layer, then only expose iterations 2, 3, 4 for 2s, then only expose 3, 4 for 2s and finally expose iteration 4 for 2 seconds. 

If this were implemented, it would only take a little bit longer than the exposure time of the longest exposure to expose all iterations instead of taking the sum of all iteration's exposure time

I hope my description is clear and I'd love to help implement this (a great reason to work on my C#)

**Comment by sn4k3** [comment] 2022-01-01 01:06
Because printers CPUs are not PC CPUs, image render takes time and then invalidate the test, you can't just wait and let resin cooldown on that time, you will get different properties than curing all at once.
Currently it's already very optimized, if you want to futher optimize, use the following setting:
![image](https://user-images.githubusercontent.com/113281/147841985-51df8db1-b437-4229-8f30-471032f9b193.png)

Duplicate of: https://github.com/sn4k3/UVtools/issues/183

**Closed** 2022-01-01 01:25 UTC
Labels: duplicate, enhancement
