### ISSUE TITLE
[BUG] 3.7.2 nonexistent islands

### ISSUE THREAD

**Issue by antwal** [sn4k3/UVtools#591] opened 2022-10-27 06:24 UTC
## System
 - OS: macOS Catalina 10.15.7
 - Slicer: Lychee Slicer
 - Printer: Elegoo Saturn
 - UVtools version: 3.7.2

```
UVtools v3.7.2 X64
Operative system: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 X64
Processor: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Processor cores: 16
Memory RAM: 22.59 / 62.96 GB
Runtime: osx.10.15-x64
Framework: .NET 6.0.10
AvaloniaUI: 0.10.18
OpenCV: 4.5.4-235

Sreens, resolution, working area, usable area:
1: 2560 x 1440 @ 200% (Primary)
    WA: 2560 x 1417    UA: 1280 x 708
2: 2560 x 1440 @ 200%
    WA: 2560 x 1417    UA: 1280 x 708
3: 2560 x 1440 @ 200%
    WA: 2560 x 1417    UA: 1280 x 708

Path:       /Applications/UVtools 3.7.2.app/Contents/MacOS/
Executable: /Applications/UVtools 3.7.2.app/Contents/MacOS/UVtools
Loaded file: Ashe_Others_2.ctb [Version: 2] [Class: ChituboxFile]

```

## Describe the bug
nonexistent islands are found, two examples attached in the screenshots

## Screenshots
<img width="2550" alt="Schermata 2022-10-27 alle 08 18 53" src="https://user-images.githubusercontent.com/410736/198206930-c3e07f82-a7cd-4778-8b1d-10b376584e4d.png">
<img width="2546" alt="Schermata 2022-10-27 alle 08 19 04" src="https://user-images.githubusercontent.com/410736/198206958-c47278d3-ca69-42e0-bd26-4584db827ba1.png">

<img width="2549" alt="Schermata 2022-10-27 alle 08 19 25" src="https://user-images.githubusercontent.com/410736/198206977-6347e8b2-8ace-4636-a277-198c60b63be2.png">
<img width="2549" alt="Schermata 2022-10-27 alle 08 19 33" src="https://user-images.githubusercontent.com/410736/198206989-422b53d5-2e7a-410d-ae1b-12a207d30ccf.png">

**Comment by antwal** [comment] 2022-10-27 06:31
with the previous version I used 3.6.3 it worked perfectly

<img width="2514" alt="Schermata 2022-10-27 alle 08 27 39" src="https://user-images.githubusercontent.com/410736/198207848-5d386d22-6437-4040-a31b-398823fe09bf.png">

I also tried 3.7.1 but it generates the same problem, it signals islands that don't really exist

<img width="2533" alt="Schermata 2022-10-27 alle 08 30 44" src="https://user-images.githubusercontent.com/410736/198208262-7937826f-0d39-41bb-9ba3-96e644241d79.png">

**Comment by antwal** [comment] 2022-10-27 06:40
I have also tried with other versions but the same problem occurs

3.7.0 same problem
<img width="2525" alt="Schermata 2022-10-27 alle 08 36 50" src="https://user-images.githubusercontent.com/410736/198209656-1d3f572d-0274-4741-a09c-39c2992954ec.png">

3.6.8 same problem
<img width="2322" alt="Schermata 2022-10-27 alle 08 38 48" src="https://user-images.githubusercontent.com/410736/198209685-11b2f832-1641-44a6-8c24-4aae56350f98.png">

**Comment by antwal** [comment] 2022-10-27 06:49
To verify the problem I am attaching the ctb file: [Download](https://file.io/ll07FaxG4PAF)

**Comment by sn4k3** [comment] 2022-10-27 12:13
Duplicate of https://github.com/sn4k3/UVtools/issues/573 -- Read explaination

**Closed** 2022-10-30 00:19 UTC
Labels: duplicate
