### ISSUE TITLE
[BUG] Menu bar options don't stay open on MacOS

### ISSUE THREAD

**Issue by bgyarfas** [sn4k3/UVtools#337] opened 2021-11-04 01:53 UTC
## System
 - OS: Mac OS 11.6
 - Slicer: NA
 - Printer: NA
 - UVtools version: 2.24.1

## Describe the bug
When clicking any of the menu items (File, Tools, Calibration, etc) they will flash for a moment and then disappear. I confirmed this is only with the 2.24.1 release.

**Comment by sn4k3** [comment] 2021-11-04 01:55
Looks like a bug on current UI framework which have been updated to the new version on this release, i will report this to them.

**Comment by bgyarfas** [comment] 2021-11-04 01:59
Done! Thanks!

**Comment by tirendel** [comment] 2021-11-04 18:41
I just confirmed this with version 2.24.0 as well. Running MacOS Monterey (Version 12.0.1); MacBook Pro 15-inch, 2017

**Comment by sn4k3** [comment] 2021-11-04 18:52
> I just confirmed this with version 2.24.0 as well. Running MacOS Monterey (Version 12.0.1); MacBook Pro 15-inch, 2017

2.24.0 is almost the same as 2.24.1 so bug is present on both. Downgrade while we wait for a fix from Avalonia

**Comment by sn4k3** [comment] 2021-11-14 17:31
This was fixed by UI framework version downgrade to 10.8

**Closed by sn4k3** 2021-11-14 17:31 UTC
Labels: external bug
