### ISSUE TITLE
[Bug] Can't load spliced file into UVTools

### ISSUE THREAD

**Issue by VingloLeClerc** [sn4k3/UVtools#723] opened 2023-06-07 14:50 UTC
### System

```Text
UVtools v3.14.1 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz
Processor cores: 8
Memory RAM: 13.69 / 15.89 GB
Runtime: win10-x64
Framework: .NET 6.0.16
AvaloniaUI: 0.10.21
OpenCV: 4.7.0

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
```

### Printer and Slicer

- Printer: Anycubic Photon Mono
- Slicer: Lychee 5.1.80

### Description of the bug

Cannot load the sliced file.
![UV Tools Error - Dhow](https://github.com/sn4k3/UVtools/assets/135844263/1944d8d2-b190-411f-82eb-00461fd92a34)

### How to reproduce

Load the file.

### Files

https://www.dropbox.com/s/da022jor64toson/Dhow-Stern-B-v2.0%20Manually%20supported%204SFaLiTe.pwmo.zip?dl=0

**Comment by sn4k3** [comment] 2023-06-07 15:04
Duplicate of https://github.com/sn4k3/UVtools/issues/719, update lychee slicer to the latest version.

**Closed** 2023-06-10 23:09 UTC
Labels: duplicate
