### ISSUE TITLE
[Bug] System.IO.Compression.Native is missing

### ISSUE THREAD

**Issue by Gruntsky** [sn4k3/UVtools#957] opened 2024-12-19 03:51 UTC
### System

```Text
UVtools v5.0.0 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: AMD Ryzen 5 3600 6-Core Processor              
Processor cores: 12
Memory RAM: 10.71 / 31.89 GB
Runtime: win-x64
Framework: .NET 9.0.0
AvaloniaUI: 11.2.2
OpenCV: 4.9.0

Path:       E:\UVTools\
Executable: E:\UVTools\UVtools.exe
Loaded file: BackUV.goo [Version: 0] [Class: GooFile]
```

### Printer and Slicer

- Printer: Saturn 4 Ultra
- Slicer: Lychee

### Description of the bug

Updated to newest version, now when I try to save an edited file I receive this error:
![UV1](https://github.com/user-attachments/assets/3a938118-ec23-4a7c-b059-b00fb583d1e4)
Uninstalled UVTools and re-installed, received the same error upon saving.

### How to reproduce

1. Go to file.
2. Click Save

**Comment by mjf55** [comment] 2024-12-19 04:15
I have the same issue.   installed V5 and when I go to launch UVTools, I get the same crash report as Gruntsky

**Comment by sn4k3** [comment] 2024-12-19 04:15
I get an error while saving goo file but is different from yours.
On your error I can see that you are opening an SL1 file and not saving a goo file.
If you you can please send me the problematic file.

Also try to replace this file on instalation folder and report back: [UVtools.Core.zip](https://github.com/user-attachments/files/18192294/UVtools.Core.zip)

**Comment by mjf55** [comment] 2024-12-19 04:23
I tried your UVTools-core dll my my issue, but no change.  My issue shows on launch.  Do you want me to create a different issue?

**Comment by sn4k3** [comment] 2024-12-19 04:27
> Do you want me to create a different issue?

No, it may be related to the OP, as the launch it open the SL1 file which is a ZIP.
I tried to open UVtools with demo file but works fine on my PC.

Let me find some information about this. Meanwhile revert back to previous version.

**Comment by sn4k3** [comment] 2024-12-19 04:31
Looks like the problem is the missing `System.IO.Compression.Native.dll` which I have no my PC but is not on UVtools folder, somehow it was not copied by the compiler... Need to find why.

**Comment by Gruntsky** [comment] 2024-12-19 04:38
Just replaced the .dll file and opened the file. Save looks to have worked with the new .dll

**Comment by sn4k3** [comment] 2024-12-19 04:49
@mjf55 I just downloaded the v5 zip and Native.dll is there... I also reinstalled via MSI and I got the native dll in my folder.
Can you confirm the presence of `System.IO.Compression.Native.dll` on your installation folder?

**Comment by Gruntsky** [comment] 2024-12-19 04:51
Yes, I can confirm System.IO.Compression.Native.dll is present in installation folder
![Uploading UV2.PNG…]()

**Comment by sn4k3** [comment] 2024-12-19 05:01
Found the cause: https://github.com/dotnet/runtime/issues/82518
NET 6 use this dll as v42, that was a wrong version which they fixed on NET7, meaning MSI won't upgrade the file because version is lower. @Gruntsky have the new Native.dll because he reinstalled UVtools which cleans and put all files without checking for upgrade.

For who land here, Uninstall UVtools and Reinstall.

**Closed** 2024-12-19 05:32 UTC
